version: "3"
services:
  web_purpleproject:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3026:3000"
    volumes: 
      - ./purpleproject:/opt/app
      - gem_cache_purpleproject:/gems
    env_file: 
      - .env/development/database_purpleproject
      - .env/development/web_purpleproject
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_purpleproject
    networks:
      - network
  webpack_dev_server_purpleproject:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3061:3061"
    volumes: 
      - ./purpleproject:/opt/app
      - gem_cache_purpleproject:/gems
    env_file: 
      - .env/development/database_purpleproject
      - .env/development/web_purpleproject
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    networks:
      - network
  database_purpleproject:
    image: postgres
    env_file: 
      - .env/development/database_purpleproject
    volumes: 
      - db_data_purpleproject:/var/lib/postgresql/data
    networks:
      - network
volumes: 
  db_data_purpleproject:
  gem_cache_purpleproject:
networks:
  network: